spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products
          predicates:
            - Path=/api/v1/products/**
          uri: lb://PRODUCTS
          filters:
            - AuthenticationFilter

        - id: categories
          predicates:
            - Path=/api/v1/categories/**
          uri: lb://CATEGORIES
          filters:
            - AuthenticationFilter


        - id: auth
          predicates:
            - Path=/auth/**
          uri: lb://AUTHENTICATION
server:
  port : 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8085/eureka